requires:
  - kro
  - flux-source
  - flux-kustomize

prepare:
  components:
    - constructor: component-constructor.yaml
      copyResources: true

deploy:
  - apply: bootstrap.yaml
  - waitFor:
      kind: rgd
      name: ${SCENARIO_SIMPLE_NAME}
      conditions: [create, condition=Ready=true]
  - apply: instance.yaml

assert:
  resources:
    - kind: deployment.apps
      name: ${SCENARIO_SIMPLE_NAME}-podinfo
      waitFor: [create, condition=Available]
      pods:
        selector: app.kubernetes.io/name=${SCENARIO_SIMPLE_NAME}-podinfo
        condition: condition=Ready=true
  fieldEquals:
    - resource: pod -l app.kubernetes.io/name=${SCENARIO_SIMPLE_NAME}-podinfo
      jsonPath: "'{.items[0].spec.containers[0].image}'"
      value: ${IMAGE_REGISTRY_HOST}/stefanprodan/podinfo:6.9.1
    - resource: pod -l app.kubernetes.io/name=${SCENARIO_SIMPLE_NAME}-podinfo
      jsonPath: "'{.items[0].spec.containers[0].env[?(@.name==\"PODINFO_UI_MESSAGE\")].value}'"
      value: ${SCENARIO_SIMPLE_NAME}

debug:
  - kubectl: get pods -n flux-system -o wide
    label: flux-pods
  - kubectl: get events -n flux-system --sort-by=.lastTimestamp
    label: flux-events
  - kubectl: get helmrelease -A -o wide
    label: helmreleases
  - kubectl: get ocirepository -A -o wide
    label: ocirepositories
  - kubectl: get kustomization -A -o wide
    label: kustomizations
