//go:build !ignore_autogenerated
// +build !ignore_autogenerated

// Code generated by deepcopy-gen-v0.36. DO NOT EDIT.

package v1alpha1

import (
	v2 "ocm.software/open-component-model/bindings/go/descriptor/v2"
	runtime "ocm.software/open-component-model/bindings/go/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DownloadWgetResource) DeepCopyInto(out *DownloadWgetResource) {
	*out = *in
	out.Type = in.Type
	if in.Spec != nil {
		in, out := &in.Spec, &out.Spec
		*out = new(DownloadWgetResourceSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.Output != nil {
		in, out := &in.Output, &out.Output
		*out = new(DownloadWgetResourceOutput)
		(*in).DeepCopyInto(*out)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DownloadWgetResource.
func (in *DownloadWgetResource) DeepCopy() *DownloadWgetResource {
	if in == nil {
		return nil
	}
	out := new(DownloadWgetResource)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyTyped is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Typed.
func (in *DownloadWgetResource) DeepCopyTyped() runtime.Typed {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DownloadWgetResourceOutput) DeepCopyInto(out *DownloadWgetResourceOutput) {
	*out = *in
	out.File = in.File
	if in.Resource != nil {
		in, out := &in.Resource, &out.Resource
		*out = new(v2.Resource)
		(*in).DeepCopyInto(*out)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DownloadWgetResourceOutput.
func (in *DownloadWgetResourceOutput) DeepCopy() *DownloadWgetResourceOutput {
	if in == nil {
		return nil
	}
	out := new(DownloadWgetResourceOutput)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DownloadWgetResourceSpec) DeepCopyInto(out *DownloadWgetResourceSpec) {
	*out = *in
	if in.Resource != nil {
		in, out := &in.Resource, &out.Resource
		*out = new(v2.Resource)
		(*in).DeepCopyInto(*out)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DownloadWgetResourceSpec.
func (in *DownloadWgetResourceSpec) DeepCopy() *DownloadWgetResourceSpec {
	if in == nil {
		return nil
	}
	out := new(DownloadWgetResourceSpec)
	in.DeepCopyInto(out)
	return out
}
