//go:build !ignore_autogenerated
// +build !ignore_autogenerated

// Code generated by deepcopy-gen-v0.37. DO NOT EDIT.

package v1alpha1

import (
	v2 "ocm.software/open-component-model/bindings/go/descriptor/v2"
	runtime "ocm.software/open-component-model/bindings/go/runtime"
	v1 "ocm.software/open-component-model/bindings/go/wget/spec/access/v1"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DownloadWgetResource) DeepCopyInto(out *DownloadWgetResource) {
	*out = *in
	out.Type = in.Type
	if in.Spec != nil {
		in, out := &in.Spec, &out.Spec
		*out = new(DownloadWgetResourceSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.Output != nil {
		in, out := &in.Output, &out.Output
		*out = new(DownloadWgetResourceOutput)
		(*in).DeepCopyInto(*out)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DownloadWgetResource.
func (in *DownloadWgetResource) DeepCopy() *DownloadWgetResource {
	if in == nil {
		return nil
	}
	out := new(DownloadWgetResource)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyTyped is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Typed.
func (in *DownloadWgetResource) DeepCopyTyped() runtime.Typed {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DownloadWgetResourceOutput) DeepCopyInto(out *DownloadWgetResourceOutput) {
	*out = *in
	out.File = in.File
	if in.Resource != nil {
		in, out := &in.Resource, &out.Resource
		*out = new(v2.Resource)
		(*in).DeepCopyInto(*out)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DownloadWgetResourceOutput.
func (in *DownloadWgetResourceOutput) DeepCopy() *DownloadWgetResourceOutput {
	if in == nil {
		return nil
	}
	out := new(DownloadWgetResourceOutput)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DownloadWgetResourceSpec) DeepCopyInto(out *DownloadWgetResourceSpec) {
	*out = *in
	if in.Resource != nil {
		in, out := &in.Resource, &out.Resource
		*out = new(v2.Resource)
		(*in).DeepCopyInto(*out)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DownloadWgetResourceSpec.
func (in *DownloadWgetResourceSpec) DeepCopy() *DownloadWgetResourceSpec {
	if in == nil {
		return nil
	}
	out := new(DownloadWgetResourceSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HTTPStreaming) DeepCopyInto(out *HTTPStreaming) {
	*out = *in
	out.Type = in.Type
	if in.Spec != nil {
		in, out := &in.Spec, &out.Spec
		*out = new(HTTPStreamingSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.Output != nil {
		in, out := &in.Output, &out.Output
		*out = new(HTTPStreamingOutput)
		(*in).DeepCopyInto(*out)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HTTPStreaming.
func (in *HTTPStreaming) DeepCopy() *HTTPStreaming {
	if in == nil {
		return nil
	}
	out := new(HTTPStreaming)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyTyped is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Typed.
func (in *HTTPStreaming) DeepCopyTyped() runtime.Typed {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HTTPStreamingOutput) DeepCopyInto(out *HTTPStreamingOutput) {
	*out = *in
	if in.Resource != nil {
		in, out := &in.Resource, &out.Resource
		*out = new(v2.Resource)
		(*in).DeepCopyInto(*out)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HTTPStreamingOutput.
func (in *HTTPStreamingOutput) DeepCopy() *HTTPStreamingOutput {
	if in == nil {
		return nil
	}
	out := new(HTTPStreamingOutput)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HTTPStreamingSpec) DeepCopyInto(out *HTTPStreamingSpec) {
	*out = *in
	if in.Resource != nil {
		in, out := &in.Resource, &out.Resource
		*out = new(v2.Resource)
		(*in).DeepCopyInto(*out)
	}
	if in.Request != nil {
		in, out := &in.Request, &out.Request
		*out = new(v1.Wget)
		(*in).DeepCopyInto(*out)
	}
	if in.TargetResource != nil {
		in, out := &in.TargetResource, &out.TargetResource
		*out = new(v2.Resource)
		(*in).DeepCopyInto(*out)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HTTPStreamingSpec.
func (in *HTTPStreamingSpec) DeepCopy() *HTTPStreamingSpec {
	if in == nil {
		return nil
	}
	out := new(HTTPStreamingSpec)
	in.DeepCopyInto(out)
	return out
}
