//go:build !ignore_autogenerated
// +build !ignore_autogenerated

// Code generated by jsonschemagen. DO NOT EDIT.

package v1alpha1

import (
	_ "embed"
)

//go:embed schemas/DownloadWgetResource.schema.json
var schemaDownloadWgetResource []byte

//go:embed schemas/DownloadWgetResourceOutput.schema.json
var schemaDownloadWgetResourceOutput []byte

//go:embed schemas/DownloadWgetResourceSpec.schema.json
var schemaDownloadWgetResourceSpec []byte

// JSONSchema returns the JSON Schema for DownloadWgetResource.
func (DownloadWgetResource) JSONSchema() []byte {
	return schemaDownloadWgetResource
}

// JSONSchema returns the JSON Schema for DownloadWgetResourceOutput.
func (DownloadWgetResourceOutput) JSONSchema() []byte {
	return schemaDownloadWgetResourceOutput
}

// JSONSchema returns the JSON Schema for DownloadWgetResourceSpec.
func (DownloadWgetResourceSpec) JSONSchema() []byte {
	return schemaDownloadWgetResourceSpec
}
