//go:build !ignore_autogenerated
// +build !ignore_autogenerated

// Code generated by jsonschemagen. DO NOT EDIT.

package v1alpha1

import (
	_ "embed"
)

//go:embed schemas/DownloadWgetResource.schema.json
var schemaDownloadWgetResource []byte

//go:embed schemas/DownloadWgetResourceOutput.schema.json
var schemaDownloadWgetResourceOutput []byte

//go:embed schemas/DownloadWgetResourceSpec.schema.json
var schemaDownloadWgetResourceSpec []byte

//go:embed schemas/HTTPStreaming.schema.json
var schemaHTTPStreaming []byte

//go:embed schemas/HTTPStreamingOutput.schema.json
var schemaHTTPStreamingOutput []byte

//go:embed schemas/HTTPStreamingSpec.schema.json
var schemaHTTPStreamingSpec []byte

// JSONSchema returns the JSON Schema for DownloadWgetResource.
func (DownloadWgetResource) JSONSchema() []byte {
	return schemaDownloadWgetResource
}

// JSONSchema returns the JSON Schema for DownloadWgetResourceOutput.
func (DownloadWgetResourceOutput) JSONSchema() []byte {
	return schemaDownloadWgetResourceOutput
}

// JSONSchema returns the JSON Schema for DownloadWgetResourceSpec.
func (DownloadWgetResourceSpec) JSONSchema() []byte {
	return schemaDownloadWgetResourceSpec
}

// JSONSchema returns the JSON Schema for HTTPStreaming.
func (HTTPStreaming) JSONSchema() []byte {
	return schemaHTTPStreaming
}

// JSONSchema returns the JSON Schema for HTTPStreamingOutput.
func (HTTPStreamingOutput) JSONSchema() []byte {
	return schemaHTTPStreamingOutput
}

// JSONSchema returns the JSON Schema for HTTPStreamingSpec.
func (HTTPStreamingSpec) JSONSchema() []byte {
	return schemaHTTPStreamingSpec
}
