//go:build !ignore_autogenerated
// +build !ignore_autogenerated

// Code generated by jsonschemagen. DO NOT EDIT.

package spec

import (
	_ "embed"
)

//go:embed schemas/ChecksumPolicy.schema.json
var schemaChecksumPolicy []byte

//go:embed schemas/Config.schema.json
var schemaConfig []byte

// JSONSchema returns the JSON Schema for ChecksumPolicy.
func (ChecksumPolicy) JSONSchema() []byte {
	return schemaChecksumPolicy
}

// JSONSchema returns the JSON Schema for Config.
func (Config) JSONSchema() []byte {
	return schemaConfig
}
