requires:
  - crossplane
  - argocd

prepare:
  components:
    - copyResources: true

deploy:
  - apply: bootstrap.yaml
    waitFor:
      - kubectl: "--for=create --for=condition=Ready=true repository/helm-argocd-crossplane-configuration-localization-repository -n default"
      - kubectl: "--for=create --for=condition=Ready=true component/helm-argocd-crossplane-configuration-localization-component -n default"
  - apply: resource.yaml
    waitFor:
      - kubectl: "--for=create --for=condition=Ready=true resource/helm-argocd-crossplane-configuration-localization-resource-xrd -n default"
  - apply: deployer.yaml
    waitFor:
      - kubectl: "--for=create --for=condition=Ready=true deployer/helm-argocd-crossplane-configuration-localization-deployer"
      - kubectl: "--for=create --for=condition=Established=true xrd/helmargocdcrossplaneconfigurationlocalizations.examples.ocm.software"
  - apply: instance.yaml
    waitFor:
      - kubectl: "--for=create --for=condition=Ready=true helmargocdcrossplaneconfigurationlocalizations/helm-argocd-crossplane-configuration-localization"
      - kubectl: "--for=create --for=jsonpath={.status.sync.status}=Synced --for=jsonpath={.status.health.status}=Healthy applications.argoproj.io/helm-argocd-crossplane-configuration-localization -n argocd"
      - kubectl: "--for=create --for=condition=Available deployment.apps/helm-argocd-crossplane-configuration-localization-podinfo -n default-argocd"
      - kubectl: "--for=condition=Ready=true pod -l app.kubernetes.io/name=helm-argocd-crossplane-configuration-localization-podinfo -n default-argocd"

assert:
  fieldEquals:
    - resource: pod -n default-argocd -l app.kubernetes.io/name=helm-argocd-crossplane-configuration-localization-podinfo
      jsonPath: "'{.items[0].spec.containers[0].image}'"
      value: ${IMAGE_REGISTRY_HOST}/stefanprodan/podinfo:6.9.1
    - resource: pod -n default-argocd -l app.kubernetes.io/name=helm-argocd-crossplane-configuration-localization-podinfo
      jsonPath: "'{.items[0].spec.containers[0].env[?(@.name==\"PODINFO_UI_MESSAGE\")].value}'"
      value: helm-argocd-crossplane-configuration-localization

debug:
  - kubectl: describe resource,components -A
    label: describe-resources-components
  - kubectl: get pods -n argocd -o wide
    label: argocd-pods
  - kubectl: get events -n argocd --sort-by=.lastTimestamp
    label: argocd-events
  - kubectl: get applications.argoproj.io -A -o wide
    label: argocd-apps
  - kubectl: logs -n argocd -l app.kubernetes.io/name=argocd-application-controller --tail=50
    label: argocd-controller-logs
  - kubectl: get xrd -A -o wide
    label: xrds
  - kubectl: get composition -A -o wide
    label: compositions
  - kubectl: get helmargocdcrossplaneconfigurationlocalizations -A -o wide
    label: instances
  - kubectl: get object.kubernetes.crossplane.io -A -o wide
    label: objects
