apiVersion: kro.run/v1alpha1
kind: ResourceGraphDefinition
metadata:
  name: helm-argocd-signing
spec:
  schema:
    apiVersion: v1alpha1
    kind: HelmArgocdSigning
    spec:
      prefix: string | default="helm-argocd-signing"
  resources:
    - id: resourceChart
      template:
        apiVersion: delivery.ocm.software/v1alpha1
        kind: Resource
        metadata:
          name: "${schema.spec.prefix}-resource-chart-name"
        spec:
          componentRef:
            name: helm-argocd-signing-component
          resource:
            byReference:
              resource:
                name: helm-resource
          additionalStatusFields:
            registry: resource.access.toOCI().registry
            repository: resource.access.toOCI().repository
            digest: resource.access.toOCI().digest
            tag: resource.access.toOCI().tag
    - id: argocdApplication
      template:
        apiVersion: argoproj.io/v1alpha1
        kind: Application
        metadata:
          name: "${schema.spec.prefix}"
          namespace: argocd
          finalizers:
            - resources-finalizer.argocd.argoproj.io
        spec:
          project: default
          source:
            chart: podinfo
            helm:
              releaseName: ${schema.spec.prefix}
            path: .
            repoURL: oci://${resourceChart.status.additional.registry}/${resourceChart.status.additional.repository}
            targetRevision: ${resourceChart.status.additional.tag}
          destination:
            server: https://kubernetes.default.svc
            namespace: default-argocd
          syncPolicy:
            automated:
              prune: true
              selfHeal: true
            syncOptions:
              - CreateNamespace=true