//go:build !ignore_autogenerated
// +build !ignore_autogenerated

// Code generated by jsonschemagen. DO NOT EDIT.

package v1alpha1

import (
	_ "embed"
)

//go:embed schemas/TrustedRoot.schema.json
var schemaTrustedRoot []byte

// JSONSchema returns the JSON Schema for TrustedRoot.
func (TrustedRoot) JSONSchema() []byte {
	return schemaTrustedRoot
}
