requires:
  - crossplane
  - function-kro
  - flux-source
  - flux-helm

deploy:
  - apply: bootstrap.yaml
    waitFor:
      - kubectl: "--for=create --for=condition=Established=true xrd/helmfluxcdcrossplanefnckro1s.examples.ocm.software"
  - apply: instance.yaml
    waitFor:
      - kubectl: "--for=create --for=condition=Available deployment.apps/helm-fluxcd-crossplane-fnc-kro-1-podinfo"
      - kubectl: "--for=condition=Ready=true pod -l app.kubernetes.io/name=helm-fluxcd-crossplane-fnc-kro-1-podinfo"
debug:
  - kubectl: get pods -n flux-system -o wide
    label: flux-pods
  - kubectl: get events -n flux-system --sort-by=.lastTimestamp
    label: flux-events
  - kubectl: get helmrelease -A -o wide
    label: helmreleases
  - kubectl: get ocirepository -A -o wide
    label: ocirepositories
  - kubectl: get xrd -A -o wide
    label: xrds
  - kubectl: get composition -A -o wide
    label: compositions
  - kubectl: get helmfluxcdcrossplanefnckro1s -A -o wide
    label: instances
  - kubectl: get object.kubernetes.crossplane.io -A -o wide
    label: objects
  - kubectl: get function -A -o wide
    label: functions
