//go:build !ignore_autogenerated
// +build !ignore_autogenerated

// Code generated by deepcopy-gen-v0.36. DO NOT EDIT.

package testutils

import (
	runtime "ocm.software/open-component-model/bindings/go/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MockAddObjectTransformer) DeepCopyInto(out *MockAddObjectTransformer) {
	*out = *in
	out.Type = in.Type
	if in.Spec != nil {
		in, out := &in.Spec, &out.Spec
		*out = new(MockAddObjectTransformerSpec)
		**out = **in
	}
	if in.Output != nil {
		in, out := &in.Output, &out.Output
		*out = new(MockAddObjectTransformerOutput)
		**out = **in
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MockAddObjectTransformer.
func (in *MockAddObjectTransformer) DeepCopy() *MockAddObjectTransformer {
	if in == nil {
		return nil
	}
	out := new(MockAddObjectTransformer)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyTyped is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Typed.
func (in *MockAddObjectTransformer) DeepCopyTyped() runtime.Typed {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MockAddObjectTransformerOutput) DeepCopyInto(out *MockAddObjectTransformerOutput) {
	*out = *in
	out.Object = in.Object
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MockAddObjectTransformerOutput.
func (in *MockAddObjectTransformerOutput) DeepCopy() *MockAddObjectTransformerOutput {
	if in == nil {
		return nil
	}
	out := new(MockAddObjectTransformerOutput)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MockAddObjectTransformerSpec) DeepCopyInto(out *MockAddObjectTransformerSpec) {
	*out = *in
	out.Object = in.Object
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MockAddObjectTransformerSpec.
func (in *MockAddObjectTransformerSpec) DeepCopy() *MockAddObjectTransformerSpec {
	if in == nil {
		return nil
	}
	out := new(MockAddObjectTransformerSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MockCustomSchemaObject) DeepCopyInto(out *MockCustomSchemaObject) {
	*out = *in
	in.OneOfStringNumberOrNull.DeepCopyInto(&out.OneOfStringNumberOrNull)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MockCustomSchemaObject.
func (in *MockCustomSchemaObject) DeepCopy() *MockCustomSchemaObject {
	if in == nil {
		return nil
	}
	out := new(MockCustomSchemaObject)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MockCustomSchemaObjectTransformer) DeepCopyInto(out *MockCustomSchemaObjectTransformer) {
	*out = *in
	out.Type = in.Type
	if in.Spec != nil {
		in, out := &in.Spec, &out.Spec
		*out = new(MockCustomSchemaObjectTransformerSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.Output != nil {
		in, out := &in.Output, &out.Output
		*out = new(MockCustomSchemaObjectTransformerOutput)
		(*in).DeepCopyInto(*out)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MockCustomSchemaObjectTransformer.
func (in *MockCustomSchemaObjectTransformer) DeepCopy() *MockCustomSchemaObjectTransformer {
	if in == nil {
		return nil
	}
	out := new(MockCustomSchemaObjectTransformer)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyTyped is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Typed.
func (in *MockCustomSchemaObjectTransformer) DeepCopyTyped() runtime.Typed {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MockCustomSchemaObjectTransformerOutput) DeepCopyInto(out *MockCustomSchemaObjectTransformerOutput) {
	*out = *in
	if in.Object != nil {
		in, out := &in.Object, &out.Object
		*out = new(MockCustomSchemaObject)
		(*in).DeepCopyInto(*out)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MockCustomSchemaObjectTransformerOutput.
func (in *MockCustomSchemaObjectTransformerOutput) DeepCopy() *MockCustomSchemaObjectTransformerOutput {
	if in == nil {
		return nil
	}
	out := new(MockCustomSchemaObjectTransformerOutput)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MockCustomSchemaObjectTransformerSpec) DeepCopyInto(out *MockCustomSchemaObjectTransformerSpec) {
	*out = *in
	if in.Object != nil {
		in, out := &in.Object, &out.Object
		*out = new(MockCustomSchemaObject)
		(*in).DeepCopyInto(*out)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MockCustomSchemaObjectTransformerSpec.
func (in *MockCustomSchemaObjectTransformerSpec) DeepCopy() *MockCustomSchemaObjectTransformerSpec {
	if in == nil {
		return nil
	}
	out := new(MockCustomSchemaObjectTransformerSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MockGetObjectTransformer) DeepCopyInto(out *MockGetObjectTransformer) {
	*out = *in
	out.Type = in.Type
	if in.Spec != nil {
		in, out := &in.Spec, &out.Spec
		*out = new(MockGetObjectTransformerSpec)
		**out = **in
	}
	if in.Output != nil {
		in, out := &in.Output, &out.Output
		*out = new(MockGetObjectTransformerOutput)
		**out = **in
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MockGetObjectTransformer.
func (in *MockGetObjectTransformer) DeepCopy() *MockGetObjectTransformer {
	if in == nil {
		return nil
	}
	out := new(MockGetObjectTransformer)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyTyped is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Typed.
func (in *MockGetObjectTransformer) DeepCopyTyped() runtime.Typed {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MockGetObjectTransformerOutput) DeepCopyInto(out *MockGetObjectTransformerOutput) {
	*out = *in
	out.Object = in.Object
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MockGetObjectTransformerOutput.
func (in *MockGetObjectTransformerOutput) DeepCopy() *MockGetObjectTransformerOutput {
	if in == nil {
		return nil
	}
	out := new(MockGetObjectTransformerOutput)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MockGetObjectTransformerSpec) DeepCopyInto(out *MockGetObjectTransformerSpec) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MockGetObjectTransformerSpec.
func (in *MockGetObjectTransformerSpec) DeepCopy() *MockGetObjectTransformerSpec {
	if in == nil {
		return nil
	}
	out := new(MockGetObjectTransformerSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OneOfStringNumberOrNull) DeepCopyInto(out *OneOfStringNumberOrNull) {
	*out = *in
	if in.String != nil {
		in, out := &in.String, &out.String
		*out = new(string)
		**out = **in
	}
	if in.Number != nil {
		in, out := &in.Number, &out.Number
		*out = new(int)
		**out = **in
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OneOfStringNumberOrNull.
func (in *OneOfStringNumberOrNull) DeepCopy() *OneOfStringNumberOrNull {
	if in == nil {
		return nil
	}
	out := new(OneOfStringNumberOrNull)
	in.DeepCopyInto(out)
	return out
}
