//go:build !ignore_autogenerated
// +build !ignore_autogenerated

// Code generated by jsonschemagen. DO NOT EDIT.

package v1alpha1

import (
	_ "embed"
)

//go:embed schemas/SigstoreSignerIdentity.schema.json
var schemaSigstoreSignerIdentity []byte

// JSONSchema returns the JSON Schema for SigstoreSignerIdentity.
func (SigstoreSignerIdentity) JSONSchema() []byte {
	return schemaSigstoreSignerIdentity
}
