apiVersion: delivery.ocm.software/v1alpha1
kind: Resource
metadata:
  name: helm-nested-signed-crossplane-resource-xrd
spec:
  componentRef:
    name: helm-nested-signed-component
  resource:
    byReference:
      resource:
        name: crossplane-xrd
