apiVersion: delivery.ocm.software/v1alpha1
kind: Resource
metadata:
  name: helm-argocd-crossplane-nested-resource-xrd
spec:
  componentRef:
    name: helm-argocd-crossplane-nested-component
  resource:
    byReference:
      resource:
        name: crossplane-xrd
      referencePath:
        - name: nested-xrd
