//go:build !ignore_autogenerated
// +build !ignore_autogenerated

// Code generated by deepcopy-gen-v0.32. DO NOT EDIT.

package v1

import (
	json "encoding/json"

	runtime "ocm.software/open-component-model/bindings/go/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *UTF8) DeepCopyInto(out *UTF8) {
	*out = *in
	out.Type = in.Type
	if in.JSON != nil {
		in, out := &in.JSON, &out.JSON
		*out = make(json.RawMessage, len(*in))
		copy(*out, *in)
	}
	if in.FormattedJSON != nil {
		in, out := &in.FormattedJSON, &out.FormattedJSON
		*out = make(json.RawMessage, len(*in))
		copy(*out, *in)
	}
	if in.YAML != nil {
		in, out := &in.YAML, &out.YAML
		*out = make(json.RawMessage, len(*in))
		copy(*out, *in)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new UTF8.
func (in *UTF8) DeepCopy() *UTF8 {
	if in == nil {
		return nil
	}
	out := new(UTF8)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyTyped is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Typed.
func (in *UTF8) DeepCopyTyped() runtime.Typed {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}
