requires:
  - kro
  - flux-source
  - flux-kustomize

deploy:
  - apply: bootstrap.yaml
    waitFor:
      - kubectl: "--for=create --for=condition=Ready=true rgd/kustomize-fluxcd-simple"
  - apply: instance.yaml
    waitFor:
      - kubectl: "--for=create --for=condition=Available deployment.apps/kustomize-fluxcd-simple-podinfo"
      - kubectl: "--for=condition=Ready=true pod -l app.kubernetes.io/name=kustomize-fluxcd-simple-podinfo"
debug:
  - kubectl: get pods -n flux-system -o wide
    label: flux-pods
  - kubectl: get events -n flux-system --sort-by=.lastTimestamp
    label: flux-events
  - kubectl: get helmrelease -A -o wide
    label: helmreleases
  - kubectl: get ocirepository -A -o wide
    label: ocirepositories
  - kubectl: get kustomization -A -o wide
    label: kustomizations
