//go:build !ignore_autogenerated
// +build !ignore_autogenerated

// Code generated by jsonschemagen. DO NOT EDIT.

package spec

import (
	_ "embed"
)

//go:embed schemas/Config.schema.json
var schemaConfig []byte

//go:embed schemas/RepositoryPolicy.schema.json
var schemaRepositoryPolicy []byte

// JSONSchema returns the JSON Schema for Config.
func (Config) JSONSchema() []byte {
	return schemaConfig
}

// JSONSchema returns the JSON Schema for RepositoryPolicy.
func (RepositoryPolicy) JSONSchema() []byte {
	return schemaRepositoryPolicy
}
