//go:build !ignore_autogenerated
// +build !ignore_autogenerated

// Code generated by jsonschemagen. DO NOT EDIT.

package v1alpha1

import (
	_ "embed"
)

//go:embed schemas/GetGitResource.schema.json
var schemaGetGitResource []byte

//go:embed schemas/GetGitResourceOutput.schema.json
var schemaGetGitResourceOutput []byte

//go:embed schemas/GetGitResourceSpec.schema.json
var schemaGetGitResourceSpec []byte

// JSONSchema returns the JSON Schema for GetGitResource.
func (GetGitResource) JSONSchema() []byte {
	return schemaGetGitResource
}

// JSONSchema returns the JSON Schema for GetGitResourceOutput.
func (GetGitResourceOutput) JSONSchema() []byte {
	return schemaGetGitResourceOutput
}

// JSONSchema returns the JSON Schema for GetGitResourceSpec.
func (GetGitResourceSpec) JSONSchema() []byte {
	return schemaGetGitResourceSpec
}
