//go:build !ignore_autogenerated
// +build !ignore_autogenerated

// Code generated by deepcopy-gen-v0.36. DO NOT EDIT.

package v1alpha1

import (
	accessv1alpha1 "ocm.software/open-component-model/bindings/go/blob/filesystem/spec/access/v1alpha1"
	v2 "ocm.software/open-component-model/bindings/go/descriptor/v2"
	runtime "ocm.software/open-component-model/bindings/go/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ConvertHelmToOCI) DeepCopyInto(out *ConvertHelmToOCI) {
	*out = *in
	out.Type = in.Type
	if in.Spec != nil {
		in, out := &in.Spec, &out.Spec
		*out = new(ConvertHelmToOCISpec)
		(*in).DeepCopyInto(*out)
	}
	if in.Output != nil {
		in, out := &in.Output, &out.Output
		*out = new(ConvertHelmToOCIOutput)
		(*in).DeepCopyInto(*out)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ConvertHelmToOCI.
func (in *ConvertHelmToOCI) DeepCopy() *ConvertHelmToOCI {
	if in == nil {
		return nil
	}
	out := new(ConvertHelmToOCI)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyTyped is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Typed.
func (in *ConvertHelmToOCI) DeepCopyTyped() runtime.Typed {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ConvertHelmToOCIOutput) DeepCopyInto(out *ConvertHelmToOCIOutput) {
	*out = *in
	out.File = in.File
	if in.Resource != nil {
		in, out := &in.Resource, &out.Resource
		*out = new(v2.Resource)
		(*in).DeepCopyInto(*out)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ConvertHelmToOCIOutput.
func (in *ConvertHelmToOCIOutput) DeepCopy() *ConvertHelmToOCIOutput {
	if in == nil {
		return nil
	}
	out := new(ConvertHelmToOCIOutput)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ConvertHelmToOCISpec) DeepCopyInto(out *ConvertHelmToOCISpec) {
	*out = *in
	out.ChartFile = in.ChartFile
	if in.ProvFile != nil {
		in, out := &in.ProvFile, &out.ProvFile
		*out = new(accessv1alpha1.File)
		**out = **in
	}
	if in.Resource != nil {
		in, out := &in.Resource, &out.Resource
		*out = new(v2.Resource)
		(*in).DeepCopyInto(*out)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ConvertHelmToOCISpec.
func (in *ConvertHelmToOCISpec) DeepCopy() *ConvertHelmToOCISpec {
	if in == nil {
		return nil
	}
	out := new(ConvertHelmToOCISpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GetHelmChart) DeepCopyInto(out *GetHelmChart) {
	*out = *in
	out.Type = in.Type
	if in.Spec != nil {
		in, out := &in.Spec, &out.Spec
		*out = new(GetHelmChartSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.Output != nil {
		in, out := &in.Output, &out.Output
		*out = new(GetHelmChartOutput)
		(*in).DeepCopyInto(*out)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GetHelmChart.
func (in *GetHelmChart) DeepCopy() *GetHelmChart {
	if in == nil {
		return nil
	}
	out := new(GetHelmChart)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyTyped is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Typed.
func (in *GetHelmChart) DeepCopyTyped() runtime.Typed {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GetHelmChartOutput) DeepCopyInto(out *GetHelmChartOutput) {
	*out = *in
	out.ChartFile = in.ChartFile
	if in.ProvFile != nil {
		in, out := &in.ProvFile, &out.ProvFile
		*out = new(accessv1alpha1.File)
		**out = **in
	}
	if in.Resource != nil {
		in, out := &in.Resource, &out.Resource
		*out = new(v2.Resource)
		(*in).DeepCopyInto(*out)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GetHelmChartOutput.
func (in *GetHelmChartOutput) DeepCopy() *GetHelmChartOutput {
	if in == nil {
		return nil
	}
	out := new(GetHelmChartOutput)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GetHelmChartSpec) DeepCopyInto(out *GetHelmChartSpec) {
	*out = *in
	if in.Resource != nil {
		in, out := &in.Resource, &out.Resource
		*out = new(v2.Resource)
		(*in).DeepCopyInto(*out)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GetHelmChartSpec.
func (in *GetHelmChartSpec) DeepCopy() *GetHelmChartSpec {
	if in == nil {
		return nil
	}
	out := new(GetHelmChartSpec)
	in.DeepCopyInto(out)
	return out
}
