//go:build !ignore_autogenerated
// +build !ignore_autogenerated

// Code generated by jsonschemagen. DO NOT EDIT.

package v1alpha1

import (
	_ "embed"
)

//go:embed schemas/ArtifactoryUpload.schema.json
var schemaArtifactoryUpload []byte

//go:embed schemas/NexusUpload.schema.json
var schemaNexusUpload []byte

//go:embed schemas/RepositoryUploadComponentVersion.schema.json
var schemaRepositoryUploadComponentVersion []byte

//go:embed schemas/RepositoryUploadOutput.schema.json
var schemaRepositoryUploadOutput []byte

//go:embed schemas/RepositoryUploadSpec.schema.json
var schemaRepositoryUploadSpec []byte

// JSONSchema returns the JSON Schema for ArtifactoryUpload.
func (ArtifactoryUpload) JSONSchema() []byte {
	return schemaArtifactoryUpload
}

// JSONSchema returns the JSON Schema for NexusUpload.
func (NexusUpload) JSONSchema() []byte {
	return schemaNexusUpload
}

// JSONSchema returns the JSON Schema for RepositoryUploadComponentVersion.
func (RepositoryUploadComponentVersion) JSONSchema() []byte {
	return schemaRepositoryUploadComponentVersion
}

// JSONSchema returns the JSON Schema for RepositoryUploadOutput.
func (RepositoryUploadOutput) JSONSchema() []byte {
	return schemaRepositoryUploadOutput
}

// JSONSchema returns the JSON Schema for RepositoryUploadSpec.
func (RepositoryUploadSpec) JSONSchema() []byte {
	return schemaRepositoryUploadSpec
}
