//go:build !ignore_autogenerated
// +build !ignore_autogenerated

// Code generated by deepcopy-gen-v0.37. DO NOT EDIT.

package v1alpha1

import (
	v2 "ocm.software/open-component-model/bindings/go/descriptor/v2"
	runtime "ocm.software/open-component-model/bindings/go/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DownloadS3Resource) DeepCopyInto(out *DownloadS3Resource) {
	*out = *in
	out.Type = in.Type
	if in.Spec != nil {
		in, out := &in.Spec, &out.Spec
		*out = new(DownloadS3ResourceSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.Output != nil {
		in, out := &in.Output, &out.Output
		*out = new(DownloadS3ResourceOutput)
		(*in).DeepCopyInto(*out)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DownloadS3Resource.
func (in *DownloadS3Resource) DeepCopy() *DownloadS3Resource {
	if in == nil {
		return nil
	}
	out := new(DownloadS3Resource)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyTyped is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Typed.
func (in *DownloadS3Resource) DeepCopyTyped() runtime.Typed {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DownloadS3ResourceOutput) DeepCopyInto(out *DownloadS3ResourceOutput) {
	*out = *in
	out.File = in.File
	if in.Resource != nil {
		in, out := &in.Resource, &out.Resource
		*out = new(v2.Resource)
		(*in).DeepCopyInto(*out)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DownloadS3ResourceOutput.
func (in *DownloadS3ResourceOutput) DeepCopy() *DownloadS3ResourceOutput {
	if in == nil {
		return nil
	}
	out := new(DownloadS3ResourceOutput)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DownloadS3ResourceSpec) DeepCopyInto(out *DownloadS3ResourceSpec) {
	*out = *in
	if in.Resource != nil {
		in, out := &in.Resource, &out.Resource
		*out = new(v2.Resource)
		(*in).DeepCopyInto(*out)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DownloadS3ResourceSpec.
func (in *DownloadS3ResourceSpec) DeepCopy() *DownloadS3ResourceSpec {
	if in == nil {
		return nil
	}
	out := new(DownloadS3ResourceSpec)
	in.DeepCopyInto(out)
	return out
}
