//go:build !ignore_autogenerated
// +build !ignore_autogenerated

// Code generated by deepcopy-gen-v0.32. DO NOT EDIT.

package runtime

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in Identity) DeepCopyInto(out *Identity) {
	{
		in := &in
		*out = make(Identity, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
		return
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Identity.
func (in Identity) DeepCopy() Identity {
	if in == nil {
		return nil
	}
	out := new(Identity)
	in.DeepCopyInto(out)
	return *out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Raw) DeepCopyInto(out *Raw) {
	*out = *in
	out.Type = in.Type
	if in.Data != nil {
		in, out := &in.Data, &out.Data
		*out = make([]byte, len(*in))
		copy(*out, *in)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Raw.
func (in *Raw) DeepCopy() *Raw {
	if in == nil {
		return nil
	}
	out := new(Raw)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyTyped is an autogenerated deepcopy function, copying the receiver, creating a new Typed.
func (in *Raw) DeepCopyTyped() Typed {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Unstructured) DeepCopyInto(out *Unstructured) {
	clone := in.DeepCopy()
	*out = *clone
	return
}

// DeepCopyTyped is an autogenerated deepcopy function, copying the receiver, creating a new Typed.
func (in *Unstructured) DeepCopyTyped() Typed {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}
