//go:build !ignore_autogenerated
// +build !ignore_autogenerated

// Code generated by ocmtypegen. DO NOT EDIT.

package v1alpha1

import "ocm.software/open-component-model/bindings/go/runtime"

// SetType is an autogenerated setter function, useful for type inference and defaulting.
func (t *AddOCIArtifact) SetType(typ runtime.Type) {
	t.Type = typ
}

// GetType is an autogenerated getter function, useful for type inference and defaulting.
func (t *AddOCIArtifact) GetType() runtime.Type {
	return t.Type
}

// SetType is an autogenerated setter function, useful for type inference and defaulting.
func (t *CTFAddComponentVersion) SetType(typ runtime.Type) {
	t.Type = typ
}

// GetType is an autogenerated getter function, useful for type inference and defaulting.
func (t *CTFAddComponentVersion) GetType() runtime.Type {
	return t.Type
}

// SetType is an autogenerated setter function, useful for type inference and defaulting.
func (t *CTFAddLocalResource) SetType(typ runtime.Type) {
	t.Type = typ
}

// GetType is an autogenerated getter function, useful for type inference and defaulting.
func (t *CTFAddLocalResource) GetType() runtime.Type {
	return t.Type
}

// SetType is an autogenerated setter function, useful for type inference and defaulting.
func (t *CTFGetComponentVersion) SetType(typ runtime.Type) {
	t.Type = typ
}

// GetType is an autogenerated getter function, useful for type inference and defaulting.
func (t *CTFGetComponentVersion) GetType() runtime.Type {
	return t.Type
}

// SetType is an autogenerated setter function, useful for type inference and defaulting.
func (t *CTFGetLocalResource) SetType(typ runtime.Type) {
	t.Type = typ
}

// GetType is an autogenerated getter function, useful for type inference and defaulting.
func (t *CTFGetLocalResource) GetType() runtime.Type {
	return t.Type
}

// SetType is an autogenerated setter function, useful for type inference and defaulting.
func (t *GetOCIArtifact) SetType(typ runtime.Type) {
	t.Type = typ
}

// GetType is an autogenerated getter function, useful for type inference and defaulting.
func (t *GetOCIArtifact) GetType() runtime.Type {
	return t.Type
}

// SetType is an autogenerated setter function, useful for type inference and defaulting.
func (t *OCIAddComponentVersion) SetType(typ runtime.Type) {
	t.Type = typ
}

// GetType is an autogenerated getter function, useful for type inference and defaulting.
func (t *OCIAddComponentVersion) GetType() runtime.Type {
	return t.Type
}

// SetType is an autogenerated setter function, useful for type inference and defaulting.
func (t *OCIAddLocalResource) SetType(typ runtime.Type) {
	t.Type = typ
}

// GetType is an autogenerated getter function, useful for type inference and defaulting.
func (t *OCIAddLocalResource) GetType() runtime.Type {
	return t.Type
}

// SetType is an autogenerated setter function, useful for type inference and defaulting.
func (t *OCIGetComponentVersion) SetType(typ runtime.Type) {
	t.Type = typ
}

// GetType is an autogenerated getter function, useful for type inference and defaulting.
func (t *OCIGetComponentVersion) GetType() runtime.Type {
	return t.Type
}

// SetType is an autogenerated setter function, useful for type inference and defaulting.
func (t *OCIGetLocalResource) SetType(typ runtime.Type) {
	t.Type = typ
}

// GetType is an autogenerated getter function, useful for type inference and defaulting.
func (t *OCIGetLocalResource) GetType() runtime.Type {
	return t.Type
}

// SetType is an autogenerated setter function, useful for type inference and defaulting.
func (t *TransferOCIArtifact) SetType(typ runtime.Type) {
	t.Type = typ
}

// GetType is an autogenerated getter function, useful for type inference and defaulting.
func (t *TransferOCIArtifact) GetType() runtime.Type {
	return t.Type
}
