//go:build !ignore_autogenerated
// +build !ignore_autogenerated

// Code generated by deepcopy-gen-v0.36. DO NOT EDIT.

package v1alpha1

import (
	v2 "ocm.software/open-component-model/bindings/go/descriptor/v2"
	runtime "ocm.software/open-component-model/bindings/go/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AddOCIArtifact) DeepCopyInto(out *AddOCIArtifact) {
	*out = *in
	out.Type = in.Type
	if in.Spec != nil {
		in, out := &in.Spec, &out.Spec
		*out = new(AddOCIArtifactSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.Output != nil {
		in, out := &in.Output, &out.Output
		*out = new(AddOCIArtifactOutput)
		(*in).DeepCopyInto(*out)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AddOCIArtifact.
func (in *AddOCIArtifact) DeepCopy() *AddOCIArtifact {
	if in == nil {
		return nil
	}
	out := new(AddOCIArtifact)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyTyped is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Typed.
func (in *AddOCIArtifact) DeepCopyTyped() runtime.Typed {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AddOCIArtifactOutput) DeepCopyInto(out *AddOCIArtifactOutput) {
	*out = *in
	if in.Resource != nil {
		in, out := &in.Resource, &out.Resource
		*out = new(v2.Resource)
		(*in).DeepCopyInto(*out)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AddOCIArtifactOutput.
func (in *AddOCIArtifactOutput) DeepCopy() *AddOCIArtifactOutput {
	if in == nil {
		return nil
	}
	out := new(AddOCIArtifactOutput)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AddOCIArtifactSpec) DeepCopyInto(out *AddOCIArtifactSpec) {
	*out = *in
	if in.Resource != nil {
		in, out := &in.Resource, &out.Resource
		*out = new(v2.Resource)
		(*in).DeepCopyInto(*out)
	}
	out.File = in.File
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AddOCIArtifactSpec.
func (in *AddOCIArtifactSpec) DeepCopy() *AddOCIArtifactSpec {
	if in == nil {
		return nil
	}
	out := new(AddOCIArtifactSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CTFAddComponentVersion) DeepCopyInto(out *CTFAddComponentVersion) {
	*out = *in
	out.Type = in.Type
	if in.Spec != nil {
		in, out := &in.Spec, &out.Spec
		*out = new(CTFAddComponentVersionSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.Output != nil {
		in, out := &in.Output, &out.Output
		*out = new(CTFAddComponentVersionOutput)
		**out = **in
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CTFAddComponentVersion.
func (in *CTFAddComponentVersion) DeepCopy() *CTFAddComponentVersion {
	if in == nil {
		return nil
	}
	out := new(CTFAddComponentVersion)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyTyped is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Typed.
func (in *CTFAddComponentVersion) DeepCopyTyped() runtime.Typed {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CTFAddComponentVersionOutput) DeepCopyInto(out *CTFAddComponentVersionOutput) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CTFAddComponentVersionOutput.
func (in *CTFAddComponentVersionOutput) DeepCopy() *CTFAddComponentVersionOutput {
	if in == nil {
		return nil
	}
	out := new(CTFAddComponentVersionOutput)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CTFAddComponentVersionSpec) DeepCopyInto(out *CTFAddComponentVersionSpec) {
	*out = *in
	out.Repository = in.Repository
	if in.Descriptor != nil {
		in, out := &in.Descriptor, &out.Descriptor
		*out = new(v2.Descriptor)
		(*in).DeepCopyInto(*out)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CTFAddComponentVersionSpec.
func (in *CTFAddComponentVersionSpec) DeepCopy() *CTFAddComponentVersionSpec {
	if in == nil {
		return nil
	}
	out := new(CTFAddComponentVersionSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CTFAddLocalResource) DeepCopyInto(out *CTFAddLocalResource) {
	*out = *in
	out.Type = in.Type
	if in.Spec != nil {
		in, out := &in.Spec, &out.Spec
		*out = new(CTFAddLocalResourceSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.Output != nil {
		in, out := &in.Output, &out.Output
		*out = new(CTFAddLocalResourceOutput)
		(*in).DeepCopyInto(*out)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CTFAddLocalResource.
func (in *CTFAddLocalResource) DeepCopy() *CTFAddLocalResource {
	if in == nil {
		return nil
	}
	out := new(CTFAddLocalResource)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyTyped is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Typed.
func (in *CTFAddLocalResource) DeepCopyTyped() runtime.Typed {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CTFAddLocalResourceOutput) DeepCopyInto(out *CTFAddLocalResourceOutput) {
	*out = *in
	if in.Resource != nil {
		in, out := &in.Resource, &out.Resource
		*out = new(v2.Resource)
		(*in).DeepCopyInto(*out)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CTFAddLocalResourceOutput.
func (in *CTFAddLocalResourceOutput) DeepCopy() *CTFAddLocalResourceOutput {
	if in == nil {
		return nil
	}
	out := new(CTFAddLocalResourceOutput)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CTFAddLocalResourceSpec) DeepCopyInto(out *CTFAddLocalResourceSpec) {
	*out = *in
	out.Repository = in.Repository
	if in.Resource != nil {
		in, out := &in.Resource, &out.Resource
		*out = new(v2.Resource)
		(*in).DeepCopyInto(*out)
	}
	out.File = in.File
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CTFAddLocalResourceSpec.
func (in *CTFAddLocalResourceSpec) DeepCopy() *CTFAddLocalResourceSpec {
	if in == nil {
		return nil
	}
	out := new(CTFAddLocalResourceSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CTFGetComponentVersion) DeepCopyInto(out *CTFGetComponentVersion) {
	*out = *in
	out.Type = in.Type
	if in.Spec != nil {
		in, out := &in.Spec, &out.Spec
		*out = new(CTFGetComponentVersionSpec)
		**out = **in
	}
	if in.Output != nil {
		in, out := &in.Output, &out.Output
		*out = new(CTFGetComponentVersionOutput)
		(*in).DeepCopyInto(*out)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CTFGetComponentVersion.
func (in *CTFGetComponentVersion) DeepCopy() *CTFGetComponentVersion {
	if in == nil {
		return nil
	}
	out := new(CTFGetComponentVersion)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyTyped is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Typed.
func (in *CTFGetComponentVersion) DeepCopyTyped() runtime.Typed {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CTFGetComponentVersionOutput) DeepCopyInto(out *CTFGetComponentVersionOutput) {
	*out = *in
	if in.Descriptor != nil {
		in, out := &in.Descriptor, &out.Descriptor
		*out = new(v2.Descriptor)
		(*in).DeepCopyInto(*out)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CTFGetComponentVersionOutput.
func (in *CTFGetComponentVersionOutput) DeepCopy() *CTFGetComponentVersionOutput {
	if in == nil {
		return nil
	}
	out := new(CTFGetComponentVersionOutput)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CTFGetComponentVersionSpec) DeepCopyInto(out *CTFGetComponentVersionSpec) {
	*out = *in
	out.Repository = in.Repository
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CTFGetComponentVersionSpec.
func (in *CTFGetComponentVersionSpec) DeepCopy() *CTFGetComponentVersionSpec {
	if in == nil {
		return nil
	}
	out := new(CTFGetComponentVersionSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CTFGetLocalResource) DeepCopyInto(out *CTFGetLocalResource) {
	*out = *in
	out.Type = in.Type
	if in.Spec != nil {
		in, out := &in.Spec, &out.Spec
		*out = new(CTFGetLocalResourceSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.Output != nil {
		in, out := &in.Output, &out.Output
		*out = new(CTFGetLocalResourceOutput)
		(*in).DeepCopyInto(*out)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CTFGetLocalResource.
func (in *CTFGetLocalResource) DeepCopy() *CTFGetLocalResource {
	if in == nil {
		return nil
	}
	out := new(CTFGetLocalResource)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyTyped is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Typed.
func (in *CTFGetLocalResource) DeepCopyTyped() runtime.Typed {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CTFGetLocalResourceOutput) DeepCopyInto(out *CTFGetLocalResourceOutput) {
	*out = *in
	out.File = in.File
	if in.Resource != nil {
		in, out := &in.Resource, &out.Resource
		*out = new(v2.Resource)
		(*in).DeepCopyInto(*out)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CTFGetLocalResourceOutput.
func (in *CTFGetLocalResourceOutput) DeepCopy() *CTFGetLocalResourceOutput {
	if in == nil {
		return nil
	}
	out := new(CTFGetLocalResourceOutput)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CTFGetLocalResourceSpec) DeepCopyInto(out *CTFGetLocalResourceSpec) {
	*out = *in
	out.Repository = in.Repository
	if in.ResourceIdentity != nil {
		in, out := &in.ResourceIdentity, &out.ResourceIdentity
		*out = make(runtime.Identity, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CTFGetLocalResourceSpec.
func (in *CTFGetLocalResourceSpec) DeepCopy() *CTFGetLocalResourceSpec {
	if in == nil {
		return nil
	}
	out := new(CTFGetLocalResourceSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GetOCIArtifact) DeepCopyInto(out *GetOCIArtifact) {
	*out = *in
	out.Type = in.Type
	if in.Spec != nil {
		in, out := &in.Spec, &out.Spec
		*out = new(GetOCIArtifactSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.Output != nil {
		in, out := &in.Output, &out.Output
		*out = new(GetOCIArtifactOutput)
		(*in).DeepCopyInto(*out)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GetOCIArtifact.
func (in *GetOCIArtifact) DeepCopy() *GetOCIArtifact {
	if in == nil {
		return nil
	}
	out := new(GetOCIArtifact)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyTyped is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Typed.
func (in *GetOCIArtifact) DeepCopyTyped() runtime.Typed {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GetOCIArtifactOutput) DeepCopyInto(out *GetOCIArtifactOutput) {
	*out = *in
	out.File = in.File
	if in.Resource != nil {
		in, out := &in.Resource, &out.Resource
		*out = new(v2.Resource)
		(*in).DeepCopyInto(*out)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GetOCIArtifactOutput.
func (in *GetOCIArtifactOutput) DeepCopy() *GetOCIArtifactOutput {
	if in == nil {
		return nil
	}
	out := new(GetOCIArtifactOutput)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GetOCIArtifactSpec) DeepCopyInto(out *GetOCIArtifactSpec) {
	*out = *in
	if in.Resource != nil {
		in, out := &in.Resource, &out.Resource
		*out = new(v2.Resource)
		(*in).DeepCopyInto(*out)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GetOCIArtifactSpec.
func (in *GetOCIArtifactSpec) DeepCopy() *GetOCIArtifactSpec {
	if in == nil {
		return nil
	}
	out := new(GetOCIArtifactSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OCIAddComponentVersion) DeepCopyInto(out *OCIAddComponentVersion) {
	*out = *in
	out.Type = in.Type
	if in.Spec != nil {
		in, out := &in.Spec, &out.Spec
		*out = new(OCIAddComponentVersionSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.Output != nil {
		in, out := &in.Output, &out.Output
		*out = new(OCIAddComponentVersionOutput)
		**out = **in
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OCIAddComponentVersion.
func (in *OCIAddComponentVersion) DeepCopy() *OCIAddComponentVersion {
	if in == nil {
		return nil
	}
	out := new(OCIAddComponentVersion)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyTyped is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Typed.
func (in *OCIAddComponentVersion) DeepCopyTyped() runtime.Typed {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OCIAddComponentVersionOutput) DeepCopyInto(out *OCIAddComponentVersionOutput) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OCIAddComponentVersionOutput.
func (in *OCIAddComponentVersionOutput) DeepCopy() *OCIAddComponentVersionOutput {
	if in == nil {
		return nil
	}
	out := new(OCIAddComponentVersionOutput)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OCIAddComponentVersionSpec) DeepCopyInto(out *OCIAddComponentVersionSpec) {
	*out = *in
	out.Repository = in.Repository
	if in.Descriptor != nil {
		in, out := &in.Descriptor, &out.Descriptor
		*out = new(v2.Descriptor)
		(*in).DeepCopyInto(*out)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OCIAddComponentVersionSpec.
func (in *OCIAddComponentVersionSpec) DeepCopy() *OCIAddComponentVersionSpec {
	if in == nil {
		return nil
	}
	out := new(OCIAddComponentVersionSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OCIAddLocalResource) DeepCopyInto(out *OCIAddLocalResource) {
	*out = *in
	out.Type = in.Type
	if in.Spec != nil {
		in, out := &in.Spec, &out.Spec
		*out = new(OCIAddLocalResourceSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.Output != nil {
		in, out := &in.Output, &out.Output
		*out = new(OCIAddLocalResourceOutput)
		(*in).DeepCopyInto(*out)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OCIAddLocalResource.
func (in *OCIAddLocalResource) DeepCopy() *OCIAddLocalResource {
	if in == nil {
		return nil
	}
	out := new(OCIAddLocalResource)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyTyped is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Typed.
func (in *OCIAddLocalResource) DeepCopyTyped() runtime.Typed {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OCIAddLocalResourceOutput) DeepCopyInto(out *OCIAddLocalResourceOutput) {
	*out = *in
	if in.Resource != nil {
		in, out := &in.Resource, &out.Resource
		*out = new(v2.Resource)
		(*in).DeepCopyInto(*out)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OCIAddLocalResourceOutput.
func (in *OCIAddLocalResourceOutput) DeepCopy() *OCIAddLocalResourceOutput {
	if in == nil {
		return nil
	}
	out := new(OCIAddLocalResourceOutput)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OCIAddLocalResourceSpec) DeepCopyInto(out *OCIAddLocalResourceSpec) {
	*out = *in
	out.Repository = in.Repository
	if in.Resource != nil {
		in, out := &in.Resource, &out.Resource
		*out = new(v2.Resource)
		(*in).DeepCopyInto(*out)
	}
	out.File = in.File
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OCIAddLocalResourceSpec.
func (in *OCIAddLocalResourceSpec) DeepCopy() *OCIAddLocalResourceSpec {
	if in == nil {
		return nil
	}
	out := new(OCIAddLocalResourceSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OCIGetComponentVersion) DeepCopyInto(out *OCIGetComponentVersion) {
	*out = *in
	out.Type = in.Type
	if in.Spec != nil {
		in, out := &in.Spec, &out.Spec
		*out = new(OCIGetComponentVersionSpec)
		**out = **in
	}
	if in.Output != nil {
		in, out := &in.Output, &out.Output
		*out = new(OCIGetComponentVersionOutput)
		(*in).DeepCopyInto(*out)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OCIGetComponentVersion.
func (in *OCIGetComponentVersion) DeepCopy() *OCIGetComponentVersion {
	if in == nil {
		return nil
	}
	out := new(OCIGetComponentVersion)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyTyped is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Typed.
func (in *OCIGetComponentVersion) DeepCopyTyped() runtime.Typed {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OCIGetComponentVersionOutput) DeepCopyInto(out *OCIGetComponentVersionOutput) {
	*out = *in
	if in.Descriptor != nil {
		in, out := &in.Descriptor, &out.Descriptor
		*out = new(v2.Descriptor)
		(*in).DeepCopyInto(*out)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OCIGetComponentVersionOutput.
func (in *OCIGetComponentVersionOutput) DeepCopy() *OCIGetComponentVersionOutput {
	if in == nil {
		return nil
	}
	out := new(OCIGetComponentVersionOutput)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OCIGetComponentVersionSpec) DeepCopyInto(out *OCIGetComponentVersionSpec) {
	*out = *in
	out.Repository = in.Repository
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OCIGetComponentVersionSpec.
func (in *OCIGetComponentVersionSpec) DeepCopy() *OCIGetComponentVersionSpec {
	if in == nil {
		return nil
	}
	out := new(OCIGetComponentVersionSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OCIGetLocalResource) DeepCopyInto(out *OCIGetLocalResource) {
	*out = *in
	out.Type = in.Type
	if in.Spec != nil {
		in, out := &in.Spec, &out.Spec
		*out = new(OCIGetLocalResourceSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.Output != nil {
		in, out := &in.Output, &out.Output
		*out = new(OCIGetLocalResourceOutput)
		(*in).DeepCopyInto(*out)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OCIGetLocalResource.
func (in *OCIGetLocalResource) DeepCopy() *OCIGetLocalResource {
	if in == nil {
		return nil
	}
	out := new(OCIGetLocalResource)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyTyped is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Typed.
func (in *OCIGetLocalResource) DeepCopyTyped() runtime.Typed {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OCIGetLocalResourceOutput) DeepCopyInto(out *OCIGetLocalResourceOutput) {
	*out = *in
	out.File = in.File
	if in.Resource != nil {
		in, out := &in.Resource, &out.Resource
		*out = new(v2.Resource)
		(*in).DeepCopyInto(*out)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OCIGetLocalResourceOutput.
func (in *OCIGetLocalResourceOutput) DeepCopy() *OCIGetLocalResourceOutput {
	if in == nil {
		return nil
	}
	out := new(OCIGetLocalResourceOutput)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OCIGetLocalResourceSpec) DeepCopyInto(out *OCIGetLocalResourceSpec) {
	*out = *in
	out.Repository = in.Repository
	if in.ResourceIdentity != nil {
		in, out := &in.ResourceIdentity, &out.ResourceIdentity
		*out = make(runtime.Identity, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OCIGetLocalResourceSpec.
func (in *OCIGetLocalResourceSpec) DeepCopy() *OCIGetLocalResourceSpec {
	if in == nil {
		return nil
	}
	out := new(OCIGetLocalResourceSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TransferOCIArtifact) DeepCopyInto(out *TransferOCIArtifact) {
	*out = *in
	out.Type = in.Type
	if in.Spec != nil {
		in, out := &in.Spec, &out.Spec
		*out = new(TransferOCIArtifactSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.Output != nil {
		in, out := &in.Output, &out.Output
		*out = new(TransferOCIArtifactOutput)
		(*in).DeepCopyInto(*out)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TransferOCIArtifact.
func (in *TransferOCIArtifact) DeepCopy() *TransferOCIArtifact {
	if in == nil {
		return nil
	}
	out := new(TransferOCIArtifact)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyTyped is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Typed.
func (in *TransferOCIArtifact) DeepCopyTyped() runtime.Typed {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TransferOCIArtifactOutput) DeepCopyInto(out *TransferOCIArtifactOutput) {
	*out = *in
	if in.Resource != nil {
		in, out := &in.Resource, &out.Resource
		*out = new(v2.Resource)
		(*in).DeepCopyInto(*out)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TransferOCIArtifactOutput.
func (in *TransferOCIArtifactOutput) DeepCopy() *TransferOCIArtifactOutput {
	if in == nil {
		return nil
	}
	out := new(TransferOCIArtifactOutput)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TransferOCIArtifactSpec) DeepCopyInto(out *TransferOCIArtifactSpec) {
	*out = *in
	if in.Resource != nil {
		in, out := &in.Resource, &out.Resource
		*out = new(v2.Resource)
		(*in).DeepCopyInto(*out)
	}
	if in.TargetResource != nil {
		in, out := &in.TargetResource, &out.TargetResource
		*out = new(v2.Resource)
		(*in).DeepCopyInto(*out)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TransferOCIArtifactSpec.
func (in *TransferOCIArtifactSpec) DeepCopy() *TransferOCIArtifactSpec {
	if in == nil {
		return nil
	}
	out := new(TransferOCIArtifactSpec)
	in.DeepCopyInto(out)
	return out
}
