//go:build !ignore_autogenerated
// +build !ignore_autogenerated

// Code generated by jsonschemagen. DO NOT EDIT.

package v1alpha1

import (
	_ "embed"
)

//go:embed schemas/AddOCIArtifact.schema.json
var schemaAddOCIArtifact []byte

//go:embed schemas/AddOCIArtifactOutput.schema.json
var schemaAddOCIArtifactOutput []byte

//go:embed schemas/AddOCIArtifactSpec.schema.json
var schemaAddOCIArtifactSpec []byte

//go:embed schemas/CTFAddComponentVersion.schema.json
var schemaCTFAddComponentVersion []byte

//go:embed schemas/CTFAddComponentVersionOutput.schema.json
var schemaCTFAddComponentVersionOutput []byte

//go:embed schemas/CTFAddComponentVersionSpec.schema.json
var schemaCTFAddComponentVersionSpec []byte

//go:embed schemas/CTFAddLocalResource.schema.json
var schemaCTFAddLocalResource []byte

//go:embed schemas/CTFAddLocalResourceOutput.schema.json
var schemaCTFAddLocalResourceOutput []byte

//go:embed schemas/CTFAddLocalResourceSpec.schema.json
var schemaCTFAddLocalResourceSpec []byte

//go:embed schemas/CTFGetComponentVersion.schema.json
var schemaCTFGetComponentVersion []byte

//go:embed schemas/CTFGetComponentVersionOutput.schema.json
var schemaCTFGetComponentVersionOutput []byte

//go:embed schemas/CTFGetComponentVersionSpec.schema.json
var schemaCTFGetComponentVersionSpec []byte

//go:embed schemas/CTFGetLocalResource.schema.json
var schemaCTFGetLocalResource []byte

//go:embed schemas/CTFGetLocalResourceOutput.schema.json
var schemaCTFGetLocalResourceOutput []byte

//go:embed schemas/CTFGetLocalResourceSpec.schema.json
var schemaCTFGetLocalResourceSpec []byte

//go:embed schemas/GetOCIArtifact.schema.json
var schemaGetOCIArtifact []byte

//go:embed schemas/GetOCIArtifactOutput.schema.json
var schemaGetOCIArtifactOutput []byte

//go:embed schemas/GetOCIArtifactSpec.schema.json
var schemaGetOCIArtifactSpec []byte

//go:embed schemas/OCIAddComponentVersion.schema.json
var schemaOCIAddComponentVersion []byte

//go:embed schemas/OCIAddComponentVersionOutput.schema.json
var schemaOCIAddComponentVersionOutput []byte

//go:embed schemas/OCIAddComponentVersionSpec.schema.json
var schemaOCIAddComponentVersionSpec []byte

//go:embed schemas/OCIAddLocalResource.schema.json
var schemaOCIAddLocalResource []byte

//go:embed schemas/OCIAddLocalResourceOutput.schema.json
var schemaOCIAddLocalResourceOutput []byte

//go:embed schemas/OCIAddLocalResourceSpec.schema.json
var schemaOCIAddLocalResourceSpec []byte

//go:embed schemas/OCIGetComponentVersion.schema.json
var schemaOCIGetComponentVersion []byte

//go:embed schemas/OCIGetComponentVersionOutput.schema.json
var schemaOCIGetComponentVersionOutput []byte

//go:embed schemas/OCIGetComponentVersionSpec.schema.json
var schemaOCIGetComponentVersionSpec []byte

//go:embed schemas/OCIGetLocalResource.schema.json
var schemaOCIGetLocalResource []byte

//go:embed schemas/OCIGetLocalResourceOutput.schema.json
var schemaOCIGetLocalResourceOutput []byte

//go:embed schemas/OCIGetLocalResourceSpec.schema.json
var schemaOCIGetLocalResourceSpec []byte

//go:embed schemas/TransferOCIArtifact.schema.json
var schemaTransferOCIArtifact []byte

//go:embed schemas/TransferOCIArtifactOutput.schema.json
var schemaTransferOCIArtifactOutput []byte

//go:embed schemas/TransferOCIArtifactSpec.schema.json
var schemaTransferOCIArtifactSpec []byte

// JSONSchema returns the JSON Schema for AddOCIArtifact.
func (AddOCIArtifact) JSONSchema() []byte {
	return schemaAddOCIArtifact
}

// JSONSchema returns the JSON Schema for AddOCIArtifactOutput.
func (AddOCIArtifactOutput) JSONSchema() []byte {
	return schemaAddOCIArtifactOutput
}

// JSONSchema returns the JSON Schema for AddOCIArtifactSpec.
func (AddOCIArtifactSpec) JSONSchema() []byte {
	return schemaAddOCIArtifactSpec
}

// JSONSchema returns the JSON Schema for CTFAddComponentVersion.
func (CTFAddComponentVersion) JSONSchema() []byte {
	return schemaCTFAddComponentVersion
}

// JSONSchema returns the JSON Schema for CTFAddComponentVersionOutput.
func (CTFAddComponentVersionOutput) JSONSchema() []byte {
	return schemaCTFAddComponentVersionOutput
}

// JSONSchema returns the JSON Schema for CTFAddComponentVersionSpec.
func (CTFAddComponentVersionSpec) JSONSchema() []byte {
	return schemaCTFAddComponentVersionSpec
}

// JSONSchema returns the JSON Schema for CTFAddLocalResource.
func (CTFAddLocalResource) JSONSchema() []byte {
	return schemaCTFAddLocalResource
}

// JSONSchema returns the JSON Schema for CTFAddLocalResourceOutput.
func (CTFAddLocalResourceOutput) JSONSchema() []byte {
	return schemaCTFAddLocalResourceOutput
}

// JSONSchema returns the JSON Schema for CTFAddLocalResourceSpec.
func (CTFAddLocalResourceSpec) JSONSchema() []byte {
	return schemaCTFAddLocalResourceSpec
}

// JSONSchema returns the JSON Schema for CTFGetComponentVersion.
func (CTFGetComponentVersion) JSONSchema() []byte {
	return schemaCTFGetComponentVersion
}

// JSONSchema returns the JSON Schema for CTFGetComponentVersionOutput.
func (CTFGetComponentVersionOutput) JSONSchema() []byte {
	return schemaCTFGetComponentVersionOutput
}

// JSONSchema returns the JSON Schema for CTFGetComponentVersionSpec.
func (CTFGetComponentVersionSpec) JSONSchema() []byte {
	return schemaCTFGetComponentVersionSpec
}

// JSONSchema returns the JSON Schema for CTFGetLocalResource.
func (CTFGetLocalResource) JSONSchema() []byte {
	return schemaCTFGetLocalResource
}

// JSONSchema returns the JSON Schema for CTFGetLocalResourceOutput.
func (CTFGetLocalResourceOutput) JSONSchema() []byte {
	return schemaCTFGetLocalResourceOutput
}

// JSONSchema returns the JSON Schema for CTFGetLocalResourceSpec.
func (CTFGetLocalResourceSpec) JSONSchema() []byte {
	return schemaCTFGetLocalResourceSpec
}

// JSONSchema returns the JSON Schema for GetOCIArtifact.
func (GetOCIArtifact) JSONSchema() []byte {
	return schemaGetOCIArtifact
}

// JSONSchema returns the JSON Schema for GetOCIArtifactOutput.
func (GetOCIArtifactOutput) JSONSchema() []byte {
	return schemaGetOCIArtifactOutput
}

// JSONSchema returns the JSON Schema for GetOCIArtifactSpec.
func (GetOCIArtifactSpec) JSONSchema() []byte {
	return schemaGetOCIArtifactSpec
}

// JSONSchema returns the JSON Schema for OCIAddComponentVersion.
func (OCIAddComponentVersion) JSONSchema() []byte {
	return schemaOCIAddComponentVersion
}

// JSONSchema returns the JSON Schema for OCIAddComponentVersionOutput.
func (OCIAddComponentVersionOutput) JSONSchema() []byte {
	return schemaOCIAddComponentVersionOutput
}

// JSONSchema returns the JSON Schema for OCIAddComponentVersionSpec.
func (OCIAddComponentVersionSpec) JSONSchema() []byte {
	return schemaOCIAddComponentVersionSpec
}

// JSONSchema returns the JSON Schema for OCIAddLocalResource.
func (OCIAddLocalResource) JSONSchema() []byte {
	return schemaOCIAddLocalResource
}

// JSONSchema returns the JSON Schema for OCIAddLocalResourceOutput.
func (OCIAddLocalResourceOutput) JSONSchema() []byte {
	return schemaOCIAddLocalResourceOutput
}

// JSONSchema returns the JSON Schema for OCIAddLocalResourceSpec.
func (OCIAddLocalResourceSpec) JSONSchema() []byte {
	return schemaOCIAddLocalResourceSpec
}

// JSONSchema returns the JSON Schema for OCIGetComponentVersion.
func (OCIGetComponentVersion) JSONSchema() []byte {
	return schemaOCIGetComponentVersion
}

// JSONSchema returns the JSON Schema for OCIGetComponentVersionOutput.
func (OCIGetComponentVersionOutput) JSONSchema() []byte {
	return schemaOCIGetComponentVersionOutput
}

// JSONSchema returns the JSON Schema for OCIGetComponentVersionSpec.
func (OCIGetComponentVersionSpec) JSONSchema() []byte {
	return schemaOCIGetComponentVersionSpec
}

// JSONSchema returns the JSON Schema for OCIGetLocalResource.
func (OCIGetLocalResource) JSONSchema() []byte {
	return schemaOCIGetLocalResource
}

// JSONSchema returns the JSON Schema for OCIGetLocalResourceOutput.
func (OCIGetLocalResourceOutput) JSONSchema() []byte {
	return schemaOCIGetLocalResourceOutput
}

// JSONSchema returns the JSON Schema for OCIGetLocalResourceSpec.
func (OCIGetLocalResourceSpec) JSONSchema() []byte {
	return schemaOCIGetLocalResourceSpec
}

// JSONSchema returns the JSON Schema for TransferOCIArtifact.
func (TransferOCIArtifact) JSONSchema() []byte {
	return schemaTransferOCIArtifact
}

// JSONSchema returns the JSON Schema for TransferOCIArtifactOutput.
func (TransferOCIArtifactOutput) JSONSchema() []byte {
	return schemaTransferOCIArtifactOutput
}

// JSONSchema returns the JSON Schema for TransferOCIArtifactSpec.
func (TransferOCIArtifactSpec) JSONSchema() []byte {
	return schemaTransferOCIArtifactSpec
}
