# Use multi-stage builds to copy certs from a minimal base image.
# Debian uses the Mozilla CA bundle which contains a maximum number of trusted CAs.
FROM --platform=$BUILDPLATFORM debian:bookworm-slim@sha256:0104b334637a5f19aa9c983a91b54c89887c0984081f2068983107a6f6c21eeb AS certs
RUN apt-get update \
    && apt-get install -y --no-install-recommends ca-certificates \
    && update-ca-certificates \
    && rm -rf /var/lib/apt/lists/*

FROM scratch
ARG TARGETOS
ARG TARGETARCH
COPY --from=certs /etc/ssl/certs/ca-certificates.crt /etc/ssl/certs/ca-certificates.crt
COPY tmp/bin/ocm-${TARGETOS}-${TARGETARCH} /ocm
ENTRYPOINT ["/ocm"]
