# Use multi-stage builds to copy certs from a minimal base image.
# Debian uses the Mozilla CA bundle which contains a maximum number of trusted CAs.
FROM --platform=$BUILDPLATFORM debian:bookworm-slim@sha256:96e378d7e6531ac9a15ad505478fcc2e69f371b10f5cdf87857c4b8188404716 AS certs
RUN apt-get update \
    && apt-get install -y --no-install-recommends ca-certificates \
    && update-ca-certificates \
    && rm -rf /var/lib/apt/lists/*

FROM scratch
ARG TARGETOS
ARG TARGETARCH
COPY --from=certs /etc/ssl/certs/ca-certificates.crt /etc/ssl/certs/ca-certificates.crt
COPY tmp/bin/ocm-${TARGETOS}-${TARGETARCH} /ocm
ENTRYPOINT ["/ocm"]
