//go:build !ignore_autogenerated
// +build !ignore_autogenerated

// Code generated by jsonschemagen. DO NOT EDIT.

package v1

import (
	_ "embed"
)

//go:embed schemas/S3.schema.json
var schemaS3 []byte

// JSONSchema returns the JSON Schema for S3.
func (S3) JSONSchema() []byte {
	return schemaS3
}
