// Code generated by ocmtypegen; DO NOT EDIT.

package test

import (
	"ocm.software/open-component-model/bindings/go/runtime"
)

// GetType returns the type definition of SampleType as per OCM's Type System.
// It is the type on which it will be registered with the dynamic type system.
func (t *SampleType) GetType() runtime.Type {
	return t.Type
}
