//go:build !ignore_autogenerated
// +build !ignore_autogenerated

// Code generated by deepcopy-gen-v0.32. DO NOT EDIT.

package test

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SampleType) DeepCopyInto(out *SampleType) {
	*out = *in
	out.Type = in.Type
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SampleType.
func (in *SampleType) DeepCopy() *SampleType {
	if in == nil {
		return nil
	}
	out := new(SampleType)
	in.DeepCopyInto(out)
	return out
}
