//go:build !ignore_autogenerated
// +build !ignore_autogenerated

// Code generated by jsonschemagen. DO NOT EDIT.

package spec

import (
	_ "embed"
)

//go:embed schemas/ArtifactoryUploaderConfig.schema.json
var schemaArtifactoryUploaderConfig []byte

//go:embed schemas/Config.schema.json
var schemaConfig []byte

//go:embed schemas/HTTPUploaderConfig.schema.json
var schemaHTTPUploaderConfig []byte

//go:embed schemas/LocalBlobUploaderConfig.schema.json
var schemaLocalBlobUploaderConfig []byte

//go:embed schemas/NexusUploaderConfig.schema.json
var schemaNexusUploaderConfig []byte

//go:embed schemas/OCIUploaderConfig.schema.json
var schemaOCIUploaderConfig []byte

//go:embed schemas/Recursive.schema.json
var schemaRecursive []byte

//go:embed schemas/ReferenceUploaderConfig.schema.json
var schemaReferenceUploaderConfig []byte

// JSONSchema returns the JSON Schema for ArtifactoryUploaderConfig.
func (ArtifactoryUploaderConfig) JSONSchema() []byte {
	return schemaArtifactoryUploaderConfig
}

// JSONSchema returns the JSON Schema for Config.
func (Config) JSONSchema() []byte {
	return schemaConfig
}

// JSONSchema returns the JSON Schema for HTTPUploaderConfig.
func (HTTPUploaderConfig) JSONSchema() []byte {
	return schemaHTTPUploaderConfig
}

// JSONSchema returns the JSON Schema for LocalBlobUploaderConfig.
func (LocalBlobUploaderConfig) JSONSchema() []byte {
	return schemaLocalBlobUploaderConfig
}

// JSONSchema returns the JSON Schema for NexusUploaderConfig.
func (NexusUploaderConfig) JSONSchema() []byte {
	return schemaNexusUploaderConfig
}

// JSONSchema returns the JSON Schema for OCIUploaderConfig.
func (OCIUploaderConfig) JSONSchema() []byte {
	return schemaOCIUploaderConfig
}

// JSONSchema returns the JSON Schema for Recursive.
func (Recursive) JSONSchema() []byte {
	return schemaRecursive
}

// JSONSchema returns the JSON Schema for ReferenceUploaderConfig.
func (ReferenceUploaderConfig) JSONSchema() []byte {
	return schemaReferenceUploaderConfig
}
