//go:build !ignore_autogenerated
// +build !ignore_autogenerated

// Code generated by deepcopy-gen-v0.37. DO NOT EDIT.

package spec

import (
	runtime "ocm.software/open-component-model/bindings/go/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ArtifactoryUploaderConfig) DeepCopyInto(out *ArtifactoryUploaderConfig) {
	*out = *in
	out.Type = in.Type
	in.MatchSpec.DeepCopyInto(&out.MatchSpec)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ArtifactoryUploaderConfig.
func (in *ArtifactoryUploaderConfig) DeepCopy() *ArtifactoryUploaderConfig {
	if in == nil {
		return nil
	}
	out := new(ArtifactoryUploaderConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyTyped is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Typed.
func (in *ArtifactoryUploaderConfig) DeepCopyTyped() runtime.Typed {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Config) DeepCopyInto(out *Config) {
	*out = *in
	out.Type = in.Type
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Config.
func (in *Config) DeepCopy() *Config {
	if in == nil {
		return nil
	}
	out := new(Config)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyTyped is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Typed.
func (in *Config) DeepCopyTyped() runtime.Typed {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HTTPUploaderConfig) DeepCopyInto(out *HTTPUploaderConfig) {
	*out = *in
	out.Type = in.Type
	in.MatchSpec.DeepCopyInto(&out.MatchSpec)
	if in.Header != nil {
		in, out := &in.Header, &out.Header
		*out = make(map[string][]string, len(*in))
		for key, val := range *in {
			var outVal []string
			if val == nil {
				(*out)[key] = nil
			} else {
				in, out := &val, &outVal
				*out = make([]string, len(*in))
				copy(*out, *in)
			}
			(*out)[key] = outVal
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HTTPUploaderConfig.
func (in *HTTPUploaderConfig) DeepCopy() *HTTPUploaderConfig {
	if in == nil {
		return nil
	}
	out := new(HTTPUploaderConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyTyped is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Typed.
func (in *HTTPUploaderConfig) DeepCopyTyped() runtime.Typed {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NexusUploaderConfig) DeepCopyInto(out *NexusUploaderConfig) {
	*out = *in
	out.Type = in.Type
	in.MatchSpec.DeepCopyInto(&out.MatchSpec)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NexusUploaderConfig.
func (in *NexusUploaderConfig) DeepCopy() *NexusUploaderConfig {
	if in == nil {
		return nil
	}
	out := new(NexusUploaderConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyTyped is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Typed.
func (in *NexusUploaderConfig) DeepCopyTyped() runtime.Typed {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *UploaderMatch) DeepCopyInto(out *UploaderMatch) {
	*out = *in
	out.AccessType = in.AccessType
	if in.ExtraIdentity != nil {
		in, out := &in.ExtraIdentity, &out.ExtraIdentity
		*out = make(runtime.Identity, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new UploaderMatch.
func (in *UploaderMatch) DeepCopy() *UploaderMatch {
	if in == nil {
		return nil
	}
	out := new(UploaderMatch)
	in.DeepCopyInto(out)
	return out
}
