//go:build !ignore_autogenerated
// +build !ignore_autogenerated

// Code generated by jsonschemagen. DO NOT EDIT.

package spec

import (
	_ "embed"
)

//go:embed schemas/Config.schema.json
var schemaConfig []byte

//go:embed schemas/CopyMode.schema.json
var schemaCopyMode []byte

//go:embed schemas/Recursive.schema.json
var schemaRecursive []byte

//go:embed schemas/UploadType.schema.json
var schemaUploadType []byte

// JSONSchema returns the JSON Schema for Config.
func (Config) JSONSchema() []byte {
	return schemaConfig
}

// JSONSchema returns the JSON Schema for CopyMode.
func (CopyMode) JSONSchema() []byte {
	return schemaCopyMode
}

// JSONSchema returns the JSON Schema for Recursive.
func (Recursive) JSONSchema() []byte {
	return schemaRecursive
}

// JSONSchema returns the JSON Schema for UploadType.
func (UploadType) JSONSchema() []byte {
	return schemaUploadType
}
