//go:build !ignore_autogenerated
// +build !ignore_autogenerated

// Code generated by jsonschemagen. DO NOT EDIT.

package spec

import (
	_ "embed"
)

//go:embed schemas/ArtifactoryUploaderConfig.schema.json
var schemaArtifactoryUploaderConfig []byte

//go:embed schemas/Config.schema.json
var schemaConfig []byte

//go:embed schemas/CopyMode.schema.json
var schemaCopyMode []byte

//go:embed schemas/HTTPUploaderConfig.schema.json
var schemaHTTPUploaderConfig []byte

//go:embed schemas/NexusUploaderConfig.schema.json
var schemaNexusUploaderConfig []byte

//go:embed schemas/Recursive.schema.json
var schemaRecursive []byte

//go:embed schemas/UploadType.schema.json
var schemaUploadType []byte

//go:embed schemas/UploaderMatch.schema.json
var schemaUploaderMatch []byte

// JSONSchema returns the JSON Schema for ArtifactoryUploaderConfig.
func (ArtifactoryUploaderConfig) JSONSchema() []byte {
	return schemaArtifactoryUploaderConfig
}

// JSONSchema returns the JSON Schema for Config.
func (Config) JSONSchema() []byte {
	return schemaConfig
}

// JSONSchema returns the JSON Schema for CopyMode.
func (CopyMode) JSONSchema() []byte {
	return schemaCopyMode
}

// JSONSchema returns the JSON Schema for HTTPUploaderConfig.
func (HTTPUploaderConfig) JSONSchema() []byte {
	return schemaHTTPUploaderConfig
}

// JSONSchema returns the JSON Schema for NexusUploaderConfig.
func (NexusUploaderConfig) JSONSchema() []byte {
	return schemaNexusUploaderConfig
}

// JSONSchema returns the JSON Schema for Recursive.
func (Recursive) JSONSchema() []byte {
	return schemaRecursive
}

// JSONSchema returns the JSON Schema for UploadType.
func (UploadType) JSONSchema() []byte {
	return schemaUploadType
}

// JSONSchema returns the JSON Schema for UploaderMatch.
func (UploaderMatch) JSONSchema() []byte {
	return schemaUploaderMatch
}
