//go:build !ignore_autogenerated
// +build !ignore_autogenerated

// Code generated by ocmtypegen. DO NOT EDIT.

package v1alpha1

import "ocm.software/open-component-model/bindings/go/runtime"

// SetType is an autogenerated setter function, useful for type inference and defaulting.
func (t *Config) SetType(typ runtime.Type) {
	t.Type = typ
}

// GetType is an autogenerated getter function, useful for type inference and defaulting.
func (t *Config) GetType() runtime.Type {
	return t.Type
}
