requires:
  - kro
  - flux-source
  - flux-helm

prepare:
  components:
    - copyResources: true

deploy:
  - apply: bootstrap.yaml
    waitFor:
      - kubectl: "--for=create --for=condition=Ready=true rgd/helm-fluxcd-configuration-localization"
  - apply: instance.yaml
    waitFor:
      - kubectl: "--for=create --for=condition=Available deployment.apps/helm-fluxcd-configuration-localization-podinfo"
      - kubectl: "--for=condition=Ready=true pod -l app.kubernetes.io/name=helm-fluxcd-configuration-localization-podinfo"

assert:
  fieldEquals:
    - resource: pod -l app.kubernetes.io/name=helm-fluxcd-configuration-localization-podinfo
      jsonPath: "'{.items[0].spec.containers[0].image}'"
      value: ${IMAGE_REGISTRY_HOST}/stefanprodan/podinfo:6.9.1
    - resource: pod -l app.kubernetes.io/name=helm-fluxcd-configuration-localization-podinfo
      jsonPath: "'{.items[0].spec.containers[0].env[?(@.name==\"PODINFO_UI_MESSAGE\")].value}'"
      value: helm-fluxcd-configuration-localization

debug:
  - kubectl: get pods -n flux-system -o wide
    label: flux-pods
  - kubectl: get events -n flux-system --sort-by=.lastTimestamp
    label: flux-events
  - kubectl: get helmrelease -A -o wide
    label: helmreleases
  - kubectl: get ocirepository -A -o wide
    label: ocirepositories
  - kubectl: get kustomization -A -o wide
    label: kustomizations
