apiVersion: kro.run/v1alpha1
kind: HelmFluxcdConfigurationLocalization
metadata:
  name: helm-fluxcd-configuration-localization
spec:
  podinfo:
    message: "helm-fluxcd-configuration-localization"
    releaseName: "helm-fluxcd-configuration-localization"