//go:build !ignore_autogenerated
// +build !ignore_autogenerated

// Code generated by jsonschemagen. DO NOT EDIT.

package v1alpha1

import (
	_ "embed"
)

//go:embed schemas/GPGCredentials.schema.json
var schemaGPGCredentials []byte

// JSONSchema returns the JSON Schema for GPGCredentials.
func (GPGCredentials) JSONSchema() []byte {
	return schemaGPGCredentials
}
