//go:build !ignore_autogenerated
// +build !ignore_autogenerated

// Code generated by jsonschemagen. DO NOT EDIT.

package v1

import (
	_ "embed"
)

//go:embed schemas/WgetIdentity.schema.json
var schemaWgetIdentity []byte

// JSONSchema returns the JSON Schema for WgetIdentity.
func (WgetIdentity) JSONSchema() []byte {
	return schemaWgetIdentity
}
