requires:
  - crossplane
  - flux-source
  - flux-helm

prepare:
  components:
    - copyResources: true

deploy:
  - apply: bootstrap.yaml
    waitFor:
      - kubectl: "--for=create --for=condition=Ready=true repository/helm-fluxcd-crossplane-configuration-localization-repository -n default"
      - kubectl: "--for=create --for=condition=Ready=true component/helm-fluxcd-crossplane-configuration-localization-component -n default"
  - apply: resource.yaml
    waitFor:
      - kubectl: "--for=create --for=condition=Ready=true resource/helm-fluxcd-crossplane-configuration-localization-resource-xrd -n default"
  - apply: deployer.yaml
    waitFor:
      - kubectl: "--for=create --for=condition=Ready=true deployer/helm-fluxcd-crossplane-configuration-localization-deployer"
      - kubectl: "--for=create --for=condition=Established=true xrd/helmfluxcdcrossplaneconfigurationlocalizations.examples.ocm.software"
  - apply: instance.yaml
    waitFor:
      - kubectl: "--for=create --for=condition=Ready=true helmfluxcdcrossplaneconfigurationlocalizations/helm-fluxcd-crossplane-configuration-localization"
      - kubectl: "--for=create --for=condition=Available deployment.apps/helm-fluxcd-crossplane-configuration-localization-podinfo"
      - kubectl: "--for=condition=Ready=true pod -l app.kubernetes.io/name=helm-fluxcd-crossplane-configuration-localization-podinfo"

assert:
  fieldEquals:
    - resource: pod -l app.kubernetes.io/name=helm-fluxcd-crossplane-configuration-localization-podinfo
      jsonPath: "'{.items[0].spec.containers[0].image}'"
      value: ${IMAGE_REGISTRY_HOST}/stefanprodan/podinfo:6.9.1
    - resource: pod -l app.kubernetes.io/name=helm-fluxcd-crossplane-configuration-localization-podinfo
      jsonPath: "'{.items[0].spec.containers[0].env[?(@.name==\"PODINFO_UI_MESSAGE\")].value}'"
      value: helm-fluxcd-crossplane-configuration-localization

debug:
  - kubectl: get pods -n flux-system -o wide
    label: flux-pods
  - kubectl: get events -n flux-system --sort-by=.lastTimestamp
    label: flux-events
  - kubectl: get helmrelease -A -o wide
    label: helmreleases
  - kubectl: get ocirepository -A -o wide
    label: ocirepositories
  - kubectl: get xrd -A -o wide
    label: xrds
  - kubectl: get composition -A -o wide
    label: compositions
  - kubectl: get helmfluxcdcrossplaneconfigurationlocalizations -A -o wide
    label: instances
  - kubectl: get object.kubernetes.crossplane.io -A -o wide
    label: objects
