//go:build !ignore_autogenerated
// +build !ignore_autogenerated

// Code generated by jsonschemagen. DO NOT EDIT.

package v1

import (
	_ "embed"
)

//go:embed schemas/GitCredentials.schema.json
var schemaGitCredentials []byte

// JSONSchema returns the JSON Schema for GitCredentials.
func (GitCredentials) JSONSchema() []byte {
	return schemaGitCredentials
}
