//go:build !ignore_autogenerated
// +build !ignore_autogenerated

// Code generated by deepcopy-gen-v0.36. DO NOT EDIT.

package v1

import (
	types "ocm.software/open-component-model/bindings/go/plugin/manager/types"
	runtime "ocm.software/open-component-model/bindings/go/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CapabilitySpec) DeepCopyInto(out *CapabilitySpec) {
	*out = *in
	out.Type = in.Type
	if in.SupportedConsumerIdentityTypes != nil {
		in, out := &in.SupportedConsumerIdentityTypes, &out.SupportedConsumerIdentityTypes
		*out = make([]types.Type, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.SupportedCredentialRepositorySpecTypes != nil {
		in, out := &in.SupportedCredentialRepositorySpecTypes, &out.SupportedCredentialRepositorySpecTypes
		*out = make([]types.Type, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CapabilitySpec.
func (in *CapabilitySpec) DeepCopy() *CapabilitySpec {
	if in == nil {
		return nil
	}
	out := new(CapabilitySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyTyped is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Typed.
func (in *CapabilitySpec) DeepCopyTyped() runtime.Typed {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}
