apiVersion: delivery.ocm.software/v1alpha1
kind: Resource
metadata:
  name: helm-argocd-crossplane-configuration-localization-resource-xrd
  namespace: default
spec:
  componentRef:
    name: helm-argocd-crossplane-configuration-localization-component
  resource:
    byReference:
      resource:
        name: crossplane-xrd
