apiVersion: delivery.ocm.software/v1alpha1
kind: Deployer
metadata:
  name: helm-configuration-localization-crossplane-deployer
spec:
  resourceRef:
    name: helm-configuration-localization-crossplane-resource-xrd
    namespace: default
