requires:
  - crossplane
  - flux-source
  - flux-helm

prepare:
  components:
    - signingKey: ocm.software

deploy:
  - apply: bootstrap.yaml
    waitFor:
      - kubectl: "--for=create --for=condition=Ready=true repository/helm-fluxcd-crossplane-signing-repository -n default"
      - kubectl: "--for=create --for=condition=Ready=true component/helm-fluxcd-crossplane-signing-component -n default"
  - apply: resource.yaml
    waitFor:
      - kubectl: "--for=create --for=condition=Ready=true resource/helm-fluxcd-crossplane-signing-resource-xrd -n default"
  - apply: deployer.yaml
    waitFor:
      - kubectl: "--for=create --for=condition=Ready=true deployer/helm-fluxcd-crossplane-signing-deployer"
      - kubectl: "--for=create --for=condition=Established=true xrd/helmfluxcdcrossplanesignings.examples.ocm.software"
  - apply: instance.yaml
    waitFor:
      - kubectl: "--for=create --for=condition=Ready=true helmfluxcdcrossplanesignings/helm-fluxcd-crossplane-signing"
      - kubectl: "--for=create --for=condition=Available deployment.apps/helm-fluxcd-crossplane-signing-podinfo"
      - kubectl: "--for=condition=Ready=true pod -l app.kubernetes.io/name=helm-fluxcd-crossplane-signing-podinfo"
debug:
  - kubectl: get pods -n flux-system -o wide
    label: flux-pods
  - kubectl: get events -n flux-system --sort-by=.lastTimestamp
    label: flux-events
  - kubectl: get helmrelease -A -o wide
    label: helmreleases
  - kubectl: get ocirepository -A -o wide
    label: ocirepositories
  - kubectl: get xrd -A -o wide
    label: xrds
  - kubectl: get composition -A -o wide
    label: compositions
  - kubectl: get helmfluxcdcrossplanesignings -A -o wide
    label: instances
  - kubectl: get object.kubernetes.crossplane.io -A -o wide
    label: objects
