//go:build !ignore_autogenerated
// +build !ignore_autogenerated

// Code generated by jsonschemagen. DO NOT EDIT.

package v1

import (
	_ "embed"
)

//go:embed schemas/GitIdentity.schema.json
var schemaGitIdentity []byte

// JSONSchema returns the JSON Schema for GitIdentity.
func (GitIdentity) JSONSchema() []byte {
	return schemaGitIdentity
}
