//go:build !ignore_autogenerated
// +build !ignore_autogenerated

// Code generated by jsonschemagen. DO NOT EDIT.

package v1

import (
	_ "embed"
)

//go:embed schemas/Git.schema.json
var schemaGit []byte

// JSONSchema returns the JSON Schema for Git.
func (Git) JSONSchema() []byte {
	return schemaGit
}
