//go:build !ignore_autogenerated
// +build !ignore_autogenerated

// Code generated by deepcopy-gen-v0.34. DO NOT EDIT.

package v1

import (
	runtime "ocm.software/open-component-model/bindings/go/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OCIImage) DeepCopyInto(out *OCIImage) {
	*out = *in
	out.Type = in.Type
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OCIImage.
func (in *OCIImage) DeepCopy() *OCIImage {
	if in == nil {
		return nil
	}
	out := new(OCIImage)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyTyped is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Typed.
func (in *OCIImage) DeepCopyTyped() runtime.Typed {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OCIImageLayer) DeepCopyInto(out *OCIImageLayer) {
	*out = *in
	out.Type = in.Type
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OCIImageLayer.
func (in *OCIImageLayer) DeepCopy() *OCIImageLayer {
	if in == nil {
		return nil
	}
	out := new(OCIImageLayer)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyTyped is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Typed.
func (in *OCIImageLayer) DeepCopyTyped() runtime.Typed {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}
