//go:build !ignore_autogenerated
// +build !ignore_autogenerated

// Code generated by jsonschemagen. DO NOT EDIT.

package v1alpha1

import (
	_ "embed"
)

//go:embed schemas/OIDCIdentityToken.schema.json
var schemaOIDCIdentityToken []byte

// JSONSchema returns the JSON Schema for OIDCIdentityToken.
func (OIDCIdentityToken) JSONSchema() []byte {
	return schemaOIDCIdentityToken
}
