//go:build !ignore_autogenerated
// +build !ignore_autogenerated

// Code generated by jsonschemagen. DO NOT EDIT.

package v1alpha1

import (
	_ "embed"
)

//go:embed schemas/SigstoreVerifierIdentity.schema.json
var schemaSigstoreVerifierIdentity []byte

// JSONSchema returns the JSON Schema for SigstoreVerifierIdentity.
func (SigstoreVerifierIdentity) JSONSchema() []byte {
	return schemaSigstoreVerifierIdentity
}
