//go:build !ignore_autogenerated
// +build !ignore_autogenerated

// Code generated by jsonschemagen. DO NOT EDIT.

package v1alpha1

import (
	_ "embed"
)

//go:embed schemas/GPGIdentity.schema.json
var schemaGPGIdentity []byte

// JSONSchema returns the JSON Schema for GPGIdentity.
func (GPGIdentity) JSONSchema() []byte {
	return schemaGPGIdentity
}
