//go:build !ignore_autogenerated
// +build !ignore_autogenerated

// Code generated by jsonschemagen. DO NOT EDIT.

package v1

import (
	_ "embed"
)

//go:embed schemas/GitHubCredentials.schema.json
var schemaGitHubCredentials []byte

// JSONSchema returns the JSON Schema for GitHubCredentials.
func (GitHubCredentials) JSONSchema() []byte {
	return schemaGitHubCredentials
}
