//go:build !ignore_autogenerated
// +build !ignore_autogenerated

// Code generated by deepcopy-gen-v0.37. DO NOT EDIT.

package v1alpha1

import (
	v2 "ocm.software/open-component-model/bindings/go/descriptor/v2"
	runtime "ocm.software/open-component-model/bindings/go/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GetGitHubCommit) DeepCopyInto(out *GetGitHubCommit) {
	*out = *in
	out.Type = in.Type
	if in.Spec != nil {
		in, out := &in.Spec, &out.Spec
		*out = new(GetGitHubCommitSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.Output != nil {
		in, out := &in.Output, &out.Output
		*out = new(GetGitHubCommitOutput)
		(*in).DeepCopyInto(*out)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GetGitHubCommit.
func (in *GetGitHubCommit) DeepCopy() *GetGitHubCommit {
	if in == nil {
		return nil
	}
	out := new(GetGitHubCommit)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyTyped is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Typed.
func (in *GetGitHubCommit) DeepCopyTyped() runtime.Typed {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GetGitHubCommitOutput) DeepCopyInto(out *GetGitHubCommitOutput) {
	*out = *in
	out.File = in.File
	if in.Resource != nil {
		in, out := &in.Resource, &out.Resource
		*out = new(v2.Resource)
		(*in).DeepCopyInto(*out)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GetGitHubCommitOutput.
func (in *GetGitHubCommitOutput) DeepCopy() *GetGitHubCommitOutput {
	if in == nil {
		return nil
	}
	out := new(GetGitHubCommitOutput)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GetGitHubCommitSpec) DeepCopyInto(out *GetGitHubCommitSpec) {
	*out = *in
	if in.Resource != nil {
		in, out := &in.Resource, &out.Resource
		*out = new(v2.Resource)
		(*in).DeepCopyInto(*out)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GetGitHubCommitSpec.
func (in *GetGitHubCommitSpec) DeepCopy() *GetGitHubCommitSpec {
	if in == nil {
		return nil
	}
	out := new(GetGitHubCommitSpec)
	in.DeepCopyInto(out)
	return out
}
