name: CLI Release

run-name: CLI Release from ${{ github.ref_name }}

on:
  workflow_dispatch: {}

permissions: {}

jobs:
  print:
    name: Stub print
    runs-on: ubuntu-latest
    steps:
      - name: Print something stubby
        run: |
          echo "Hello from stubby the stubbed cli release GitHub action."