name: CLI
on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main
jobs:
  CTF:
    name: CTF
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - name: Setup Go (required for CLI build)
        uses: actions/setup-go@d35c59abb061a4a6fb18e82ac0862c26744d6ab5 # v5
        with:
          go-version-file: cli/go.mod
          cache-dependency-path: cli/go.sum
      - name: Install Task
        uses: arduino/setup-task@v2
        with:
          version: 3.x
          repo-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Generate
        run: task cli:generate/ctf
      - name: Verify
        run: task cli:verify/ctf
          
