name: Controller Release
run-name: Controller Release from ${{ github.ref_name }}

on:
  workflow_dispatch: {}

permissions: {}

jobs:
  print:
    name: Stub print
    runs-on: ubuntu-latest
    steps:
      - name: Print something stubby
        run: |
          echo "Hello from stubby the stubbed controller release GitHub action."