name: 'Mark stale issues and PRs'
on:
  schedule:
    - cron: '7 1 * * *'
  workflow_dispatch:

permissions:
  contents: read

jobs:
  stale:  # call reusable workflow from central '.github' repo
    permissions:
      issues: write
      pull-requests: write
      contents: read
    uses: open-component-model/.github/.github/workflows/stale.yml@075c873649c1b5b4bbf0b4a0947ecf6eb2e8c538 # main