name: 'Mark stale issues and PRs'
on:
  schedule:
    - cron: '7 1 * * *'
  workflow_dispatch:

permissions:
  contents: read

jobs:
  stale:  # call reusable workflow from central '.github' repo
    permissions:
      issues: write
      pull-requests: write
      contents: read
    uses: open-component-model/.github/.github/workflows/stale.yml@cb108e967074ac074142b6d22de15811803d06c5 # main
    secrets: inherit