# Trigger central Black Duck scan workflow for the Open Component Model project.
name: Trigger Blackduck Scan
on: 
  push:
    paths-ignore:
    - '.github/workflows/**'
    branches: [ "main" ]
  pull_request_target:
    paths-ignore:
    - '.github/workflows/**'
    branches: [ "main" ]
  schedule:
    - cron:  '10 0 * * 0'
  workflow_dispatch:

jobs:
  trigger-scan:
    uses: open-component-model/.github/.github/workflows/blackduck-scan.yaml@dad4f695ff2da99ad4895c8cd175fed28a84fe66
    with:
      # required to be able to differentiate between PRs and pushes in the called workflow (rapid or full scan)
      event_type: ${{ github.event_name }} 
      detector_search_depth: 3
    secrets: inherit
    permissions:
      contents: read