name: "GitHub Scripts: Verify"

on:
  pull_request:
    branches:
      - main
    paths:
      - '.github/workflows/verify-github-scripts.yml'
      - '.github/scripts/**'

permissions:
  contents: read

jobs:
  verify:
    runs-on: ubuntu-24.04-arm
    name: Lint & Test
    steps:
      - name: Checkout
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          sparse-checkout: |
            .github/scripts
          persist-credentials: false

      - name: Setup Node.js
        uses: actions/setup-node@249970729cb0ef3589644e2896645e5dc5ba9c38 # v6
        with:
          node-version-file: .github/scripts/package.json

      - name: Install dependencies
        working-directory: .github/scripts
        run: npm ci

      - name: Lint scripts
        working-directory: .github/scripts
        run: npm run lint

      - name: Run tests
        working-directory: .github/scripts
        run: npm test
